### ISSUE TITLE
Generate a work type

### ISSUE THREAD

**Issue by jmm0177** [wvulibraries/wvu_hyrax#2]
https://github.com/samvera/hyrax/blob/main/documentation/developing-your-hyrax-based-app.md#generate-a-work-type

Create work type for images to start using this metadata application profile: https://samvera.github.io/metadata_application_profile.html

**Comment by trmccormick** [comment]
Adjusted models in the rails-5-hyrax-3 branch. We setup a BasicWork model that can handle attached files of any type. Added extended metadata (/models/extended_metadata.rb) model that has our additional metadata files. This is included in the BasicWork model.
